[package]
name = "ui"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
objc2 = "0.6.4"
objc2-core-foundation = "0.3.2"
objc2-core-graphics = "0.3.2"
objc2-quartz-core = { version = "0.3.2", features = ["CALayer", "objc2-core-graphics"] }
config = { version = "0.1.0", path = "../config" }

[dependencies.objc2-foundation]
version = "0.3.2"
features = ["NSString", "NSGeometry"]

[dependencies.objc2-app-kit]
version = "0.3.2"
features = [
    "NSButton",
    "NSCell",
    "NSColor",
    "NSControl",
    "NSFont",
    "NSGraphics",
    "NSImage",
    "NSImageView",
    "NSMenu",
    "NSMenuItem",
    "NSPanel",
    "NSPopUpButton",
    "NSResponder",
    "NSRunningApplication",
    "NSScreen",
    "NSSlider",
    "NSText",
    "NSTextField",
    "NSView",
    "NSVisualEffectView",
    "NSWindow",
    "libc",
]
