[package]
name = "capture"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
objc2-core-foundation = "0.3.2"
objc2-core-graphics = "0.3.2"
skylight-sys = { path = "../skylight-sys" }
